default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: recipe_app_development
  username: dee
  password: Bbik244

test:
  <<: *default
  database: recipe_app_test
  username: dee
  password: Bbik244

production:
  <<: *default
  database: recipe_ueih
  username: recipe_ueih_user
  password: <%= ENV["RECIPE_APP_DATABASE_PASSWORD"] %>

